#!/bin/bash

# compiles JS to an executable program via C

# usage
#    compile-js-lib libraryName lib.js output.dylib

set -euo pipefail

source lib.sh

__dirname=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
runtimePath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )/runtime

main() {
    mkdir -p out/compiled
    local name=$1
    local js=$2
    local out=$3
    local cTarget=${__dirname}/out/compiled/${name}.c
    JSC_OUTPUT_LIBRARY=$name JSC_LIBRARY_HEADER=../../runtime/prelude.h JsToC $js > $cTarget
    clang -dynamiclib\
          --config ${runtimePath}/clangopts.cfg\
          -l runtime\
          -L ${runtimePath}/out\
          $cTarget -o $out
}

main $@
