#!/bin/bash

# compiles JS to an executable program

set -euo pipefail

source lib.sh

main() {
    local exe=$2
    local cTarget=out/$(basename $2).c
    JsToC $1 > $cTarget
    CToExec $cTarget $exe
}

main $@
