#!/bin/bash

# compiles JS to an executable program via C

# usage
#    compile-js-lib libraryName lib.js output.dylib

set -euo pipefail

source lib.sh

main() {
    mkdir -p out/compiled
    local name=$1
    local js=$2
    local out=$3
    local cTarget=out/compiled/${name}.c
    JSC_OUTPUT_LIBRARY=$name JSC_LIBRARY_HEADER=../../runtime/prelude.h JsToC $js > $cTarget
    CToLib $cTarget $out
}

main $@
