#!/bin/bash

set -euo pipefail

main() {
    local exe=$2
    local cTarget=out/$(basename $2).c
    node js-build/js-to-c.js $1 > $cTarget
    local runtime_libs=$(find runtime -depth 1 -name '*.c' -not -name '*.test.c')
    gcc $cTarget $runtime_libs -o $exe
    chmod a+x $exe
}

main $@