#!/bin/bash

# debug run a test executable
# usage: 
#   ./scripts/debug-system-test ./test/fixtures/some-thing.c

test=$1
output=${test/.c/} 

./runtime/scripts/c-to-exec $test $output && lldb -S ./test/lldb.conf -o run ${output}
