#!/usr/bin/env node
'use strict'

const {parseScript, Syntax} = require("esprima");
const {readFileSync} = require("fs");

main();

function main() {
  const ast = parseScript(readFileSync(process.argv[2], {encoding:'utf8'}));
  console.log(JSON.stringify(ast, null, "\t"));
}
