#!/bin/bash

# compiles a C file output by jsc into an executable file

set -euo pipefail

runtimePath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )/..

DLLEXT=so
if [[ $(uname) == "Darwin" ]]; then
    DLLEXT=dylib
fi

main() {
    local cTarget=$1
    local exe=$2
    clang --config ${runtimePath}/clangopts.cfg\
          -l prelude -L ${runtimePath}/out\
          -l runtime -L ${runtimePath}/../out\
          ${runtimePath}/out/libruntime.${DLLEXT}\
          ${runtimePath}/../out/libprelude.${DLLEXT}\
          $cTarget -o $exe
}


main $@
