#!/bin/bash

# compiles a C file output by jsc into an executable file

set -euo pipefail

runtimePath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )/..

main() {
    local cTarget=$1
    local exe=$2
    clang --config ${runtimePath}/clangopts.cfg\
          -l prelude -L ${runtimePath}/out\
          -l runtime -L ${runtimePath}/../out\
          -Wl,-rpath,${runtimePath}/out,-rpath,${runtimePath}/../out\
          $cTarget -o $exe
}


main $@
