#!/bin/bash

set -euo pipefail

main() {
  local target=$1
  nodemon --ignore lib\
          --ext 'c,h'\
          --exec "make out/${target}_test && lldb -o run ./out/${target}_test || :"
}

main $@
